name: t_server
description: TServer package for dart core lib and is support http,websocket
version: 2.2.0
homepage: https://github.com/ThanCoder/t_server
repository: https://github.com/ThanCoder/t_server

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

# Add regular dependencies here.
dependencies:
  mime: ^2.0.0
# path: ^1.8.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
